### ISSUE TITLE
Set up Redirects

### ISSUE THREAD

**Issue by d4mation** [realbig/RBM_TH_LOVEFROMLOUIE#17]

**Comment by d4mation** [comment]
Since the Slugs have largely stayed the same (And all Stories that were once Posts are auto-redirecting through WP itself if the old URL is hit), I'd say this has been taking care of naturally.

**Comment by BigActual** [comment]
Thanks for clarifying. Yes it's a generic list of to-dos so occasionally this will be skipped.
