### ISSUE TITLE
Install Plugins

### ISSUE THREAD

**Issue by d4mation** [realbig/RBM_TH_LOVEFROMLOUIE#2]
- [x] Yoast
- [x] Akismet
- [x] Gravity Forms
- [x] Stripe/PayPal, etc

**Comment by d4mation** [comment]
Looks like WooCommerce Stripe isn't available on the Multisite.

https://woocommerce.com/products/stripe/

**Comment by BigActual** [comment]
It's on the DropBox. That's a generic list btw. Install what you need with Give in play to process transactions. PayPal is fine or Stripe... Your call

**Comment by d4mation** [comment]
PayPal is default with Give and is included, so that's what we're going to use ¯\\_(ツ)\_/¯
