### ISSUE TITLE
Dropbox Photos

### ISSUE THREAD

**Issue by d4mation** [realbig/RBM_TH_LOVEFROMLOUIE#20]
I've had this problem for a while now. I mentioned it in Slack, but it overall hasn't been a problem since files were added under the Real Big Marketing folder. I'd get notifications on my Mac (and occasionally emails) about being out of space, but overall it didn't negatively impact my work.

However, if I try to add the shared folder for Love From Louie "To My Dropbox" so that I can access them, it says that I do not have enough space.

I think that Dropbox erroneously assumes that I have to have space on my account to access shared folders. I guess it makes a copy of everything into your account when it does so? I'm not sure. I am fairly certain Google Drive doesn't do that, so it would be surprising for Dropbox to do so.

I may need to instead get these photos zipped up and sent to me directly.

![image](http://i.imgur.com/PgSupE6.gif)

**Comment by d4mation** [comment]
Unfortunately, simply clicking the Shared Folder in Dropbox does not let me access the files through the web interface.

**Comment by BigActual** [comment]
DropBox went by the wayside. The client is unable bulk upload.
