### ISSUE TITLE
menu pushing behind logo as site narrows

### ISSUE THREAD

**Issue by BigActual** [realbig/RBM_TH_LOVEFROMLOUIE#26]
![image](https://cloud.githubusercontent.com/assets/8271108/25351827/ddaf0870-28f7-11e7-8d5a-83c6867c2d67.png)

**Comment by d4mation** [comment]
This is somewhat unavoidable. The only thing we could really do would be to get it to switch to use the Mobile Menu earlier than usual.

**Comment by d4mation** [comment]
Made it so that the Mobile Menu will show instead of allowing there to be an overlap. This should work.
