### ISSUE TITLE
Attach generic donation form to blog single

### ISSUE THREAD

**Issue by BigActual** [realbig/RBM_TH_LOVEFROMLOUIE#27]
Currently the system pulls in the form that defaults to "Abbie". See image:
![image](https://user-images.githubusercontent.com/8271108/31633726-4c70235e-b28f-11e7-9ffa-bd8d2c1a0a3e.png)
We need that to use a more generic title on blog single because these stories may not be so specific to a single dog. 
Let's try,  "Please Help."

**Comment by d4mation** [comment]
Should Posts instead have a different Form entirely? 

It doesn't matter really. Just a thought.

**Comment by BigActual** [comment]
I have no opinion either way.

**Comment by BigActual** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10134284-283868566_2-s4-v1.png?transparent=1&palette=1&width=75)
