### ISSUE TITLE
Receipt Issue on donation

### ISSUE THREAD

**Issue by BigActual** [realbig/RBM_TH_LOVEFROMLOUIE#28]
![image](https://user-images.githubusercontent.com/8271108/99133057-690b8300-25e6-11eb-81e1-ce75de456486.png)

**Comment by d4mation** [comment]
This seems to be a bug in the plugin. If you view https://lovefromlouie.org/donation-confirmation/?payment-confirmation=paypal&donation_id=1612 instead, it works.

I'll see if I can set up a redirect to handle this on the server side.

**Comment by d4mation** [comment]
Actually, there was an update available for the plugin. I saw nothing for this issue in the changelog, but I gave updating it a shot and it corrected the problem.
