### ISSUE TITLE
Configure Site Settings

### ISSUE THREAD

**Issue by d4mation** [realbig/RBM_TH_LOVEFROMLOUIE#4]
@BigActual What exactly do you mean by this? Just generic stuff like you'd find under Settings in the Admin?

I've found that the defaults are generally good, outside of Permalinks, which would be handled in #3.

**Comment by BigActual** [comment]
Yes, exactly this. I always just go through and double check all of them; timezone, discourage indexing, and several others.

With regard to discourage indexing, I always discourage until it's time to launch, The search engines that really matter still follow this.

**Comment by BigActual** [comment]
Do you use the media settings at all?

**Comment by d4mation** [comment]
I'll sometimes programmatically add extra Image Sizes if appropriate, but I generally leave the default ones alone.
