### ISSUE TITLE
Donate Page

### ISSUE THREAD

**Issue by d4mation** [realbig/RBM_TH_LOVEFROMLOUIE#8]

**Comment by d4mation** [comment]
@BigActual does there need to be a separate Donate page? 

Looking at the Project Description, it seems like it is going to be in 3 different places:

- Home Page as a Call to Action
- Footer (Every Page)
- Stories

Right now I have it set to show within the Sidebar as part of #10, so it ends up being on basically every page except for the Home Page as a Sidebar item. I have it showing the most Recent Story where it says "Help ____," unless you're viewing a Story, then it shows their name instead.

Give has some pretty neat configuration settings to where you can have it reveal the Fields to fill out when you click the button or it can even show them as a popup modal, so we have a lot of flexibility with it to make it fit within different parts of the site easily.

**Comment by BigActual** [comment]
I'd love to see the donation function present in three ways:
1) On it's own page
2) Able to start and complete in the Sidebar
3) start from a call to action button in content which brings up an overlay so the End User never feels as if they've left the page.

There are two pages where number three will become relevant. The home page and on the landing page I put together to receive visitors from the book/author site.

**Comment by d4mation** [comment]
I believe the "How You Can Help" page will function well as a Donation Page, actually. The Content from the current site was already set up in such a way for it. I just tweaked it to say "In the Sidebar" rather than on the right, since on Mobile "on the right" would actually be "at the bottom".

The Overlay on the Homepage is all set up now as well :+1:
