### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by d4mation** [realbig/RBM_TH_LOVEFROMLOUIE#9]

**Comment by d4mation** [comment]
@BigActual Just to clarify, this is for the eCommerce stuff, right? So just a "My Account" page then which defaults to a Login Form?

**Comment by BigActual** [comment]
Yes

**Comment by d4mation** [comment]
I had some issues with browser caching for this at first while trying to log in, but it does work.

If you have this problem, clearing the browser cache ought to do it. I switched over to Firefox (Which rarely gets used, so no cache really) and it worked just fine.

**Comment by BigActual** [comment]
For this client, the answer is yes. However, it's an item that will have fluid meaning from client to client. Some may want a personalized login screen, like Lowry. Others may want to have their logo inserted into the login screen only. Others may want all of that and a custom profile page.

**Comment by BigActual** [comment]
For this client, yes. Others may want different stuff, like custom sign on screens or personalized user profile pages.
